### ISSUE TITLE
增加被擊中動畫及死亡動畫

### ISSUE THREAD

**Issue by kent010341** [KIodine/pygame-raiden#1]
被擊中動畫：角色與子彈中間(explosion1.png)
死亡動畫：僅固定玩家，並在角色周圍產生隨機爆炸動畫(stone.png)

edit:
背景新增緩慢捲動的星空
新增replay

**Comment by KIodine** [comment]
已實作被擊動畫。

**Comment by KIodine** [comment]
已實作並改進死亡動畫。
